# These are supported funding model platforms

github: difegue
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: T6T2UP5N
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
