on: [push, pull_request]
name: "Continuous Integration \U0001F44C\U0001F440"
jobs:
  testSuite:
    name: Run Test Suite and Perl Critic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test Docker Build
      run: |
        docker build -t difegue/lanraragi -f ./tools/build/docker/Dockerfile .
    - name: LANraragi Test Suite
      uses: ./.github/action-run-tests
    - name: Perl Critic
      uses: Difegue/action-perlcritic@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: ./lib/* ./script/* ./tools/install.pl
  testBrew:
    name: Test Homebrew version
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and test bundled homebrew formula
      run: |
        brew update
        cd tools/build/homebrew
        echo "Replacing commit hash in formula with current hash $(git rev-parse --verify HEAD)"
        sed -i.bck "s/COMMIT_HASH/$(git rev-parse --verify HEAD)/" Lanraragi.rb
        brew unlink node@12
        brew install --force --verbose --build-from-source Lanraragi.rb
        brew test --verbose Lanraragi.rb 
        brew audit --verbose Lanraragi.rb
