on: [push, pull_request]
name: "Continuous Integration \U0001F44C\U0001F440"
jobs:
  testSuite:
    name: Run Test Suite and Perl Critic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test Docker Build
      run: |
        docker build -t difegue/lanraragi -f ./tools/build/docker/Dockerfile .
    - name: LANraragi Test Suite
      uses: ./.github/action-run-tests
    - name: Perl Critic
      uses: Difegue/action-perlcritic@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: ./lib/* ./script/* ./tools/install.pl
  testBrew:
    name: Test Homebrew version
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and test bundled homebrew formula
      run: |
        brew update
        tar -cvzf /tmp/lanraragi.tar.gz .
        cd tools/build/homebrew
        echo "Moving checked out'd code to the brew cache location $(brew --cache -s Lanraragi.rb)"
        cp /tmp/lanraragi.tar.gz $(brew --cache -s Lanraragi.rb)
        brew unlink node@12
        brew unlink lanraragi
        brew install --verbose --build-from-source Lanraragi.rb
        brew test --verbose Lanraragi.rb 
        brew audit --verbose Lanraragi.rb
